[package]
name = "dwrote"
version = "0.1.0"
authors = ["Vladimir Vukicevic <vladimir@pobox.com>"]

[lib]
name = "dwrote"

[dependencies]
libc = "0.2"
lazy_static = "0.2"
serde = "0.8"
winapi = "0.2"
kernel32-sys = "0.2"
dwrite-sys = "0.2"

